### ISSUE TITLE
building with go1.11 requires GO111MODULE=on set

### ISSUE THREAD

**Issue by jscook2345** [hpcng/sif#37]
Maybe this environment variable should be set in the script regardless?

```
$ ./build.sh
build flag -mod=vendor only valid when using modules
$ go version
go version go1.11.5 linux/amd64
```

```
$ env GO111MODULE=on ./build.sh
siftool version 1.0.1-60.g3cbcb48 built and installed in /home/vagrant/go/bin
```

**Comment by tri-adam** [comment]
Go has changed its stance on this front substantially since Go 1.11. As per the [Go 1.13 release notes](https://golang.org/doc/go1.13#modules):

> The `GO111MODULE` environment variable continues to default to `auto`, but the auto setting now activates the module-aware mode of the `go` command whenever the current working directory contains, or is below a directory containing, a `go.mod` file — even if the current directory is within `GOPATH/src`.

Coupled with Go 1.13 being the minimum version currently specified by SIF's stated [Go version compatibility](https://github.com/hpcng/sif#go-version-compatibility), I am closing this issue and filing it under the rare "it fixed itself" category!
